http:
  middlewares:
    real-ip-cf:
      plugin:
        real-ip:
          Proxy:
            - realIP: Cf-Connecting-Ip
              OverwriteXFF: true
    compress:
      compress:
        encodings:
          - br
          - gzip
        minResponseBodyBytes: 1024
