Listen 8888

<IfModule mod_status.c>
    ExtendedStatus On
</IfModule>

<VirtualHost *:8888>
    DocumentRoot /var/www/html
    <Location /server-status>
        SetHandler server-status
        Require all granted
    </Location>
    <Directory /var/www/html>
        AllowOverride None
        Require all denied
    </Directory>
</VirtualHost>
